// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDseF1sgUEMDW9xNzRh3Z-loCSRyxnlx0s',
    appId: '1:649230035077:web:a3b2f82d6f18e5184261ec',
    messagingSenderId: '649230035077',
    projectId: 'adruinounor4wifi',
    authDomain: 'adruinounor4wifi.firebaseapp.com',
    databaseURL: 'https://adruinounor4wifi-default-rtdb.firebaseio.com',
    storageBucket: 'adruinounor4wifi.appspot.com',
    measurementId: 'G-HBWQ16W95K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRI3wL3ItK0JVqPwHLdgNTDBjHL8dM2lM',
    appId: '1:649230035077:android:9327e9934f4a58924261ec',
    messagingSenderId: '649230035077',
    projectId: 'adruinounor4wifi',
    databaseURL: 'https://adruinounor4wifi-default-rtdb.firebaseio.com',
    storageBucket: 'adruinounor4wifi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIurElSfPnZIdbFjHs2Gf62KeQKD85qk4',
    appId: '1:649230035077:ios:9e758e216c04b8f14261ec',
    messagingSenderId: '649230035077',
    projectId: 'adruinounor4wifi',
    databaseURL: 'https://adruinounor4wifi-default-rtdb.firebaseio.com',
    storageBucket: 'adruinounor4wifi.appspot.com',
    iosBundleId: 'com.example.smartlight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIurElSfPnZIdbFjHs2Gf62KeQKD85qk4',
    appId: '1:649230035077:ios:d1b4c6356b8304034261ec',
    messagingSenderId: '649230035077',
    projectId: 'adruinounor4wifi',
    databaseURL: 'https://adruinounor4wifi-default-rtdb.firebaseio.com',
    storageBucket: 'adruinounor4wifi.appspot.com',
    iosBundleId: 'com.example.smartlight.RunnerTests',
  );
}
